In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('observation.csv')

In [3]:
df.head()

,Unnamed: 0,id,observed_on,description,latitude,longitude,map_scale,timeframe,species_guess,user_id,...,rank,ancestry,common_name,common_name_id,common_name_name,is_valid,lexicon,rank_level,medium_photo_url,coordinates_obscured
0,0,71093987,2021-03-10,NaN,48.494216,-123.347391,NaN,NaN,NaN,3945649,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
1,1,71090540,2021-03-12,NaN,49.082750,-117.801982,NaN,NaN,western redcedar,3953583,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
2,2,71090538,2021-03-12,NaN,49.082752,-117.802098,NaN,NaN,Western Redcedar,3953583,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
3,3,71090537,2021-03-12,NaN,49.082780,-117.802020,NaN,NaN,western redcedar,3953583,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
4,4,71090536,2021-03-12,NaN,49.082783,-117.801990,NaN,NaN,western redcedar,3953583,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN

In [4]:
len(df)

600

In [5]:
df.columns

Index(['Unnamed: 0', 'id', 'observed_on', 'description', 'latitude',
       'longitude', 'map_scale', 'timeframe', 'species_guess', 'user_id',
       'taxon_id', 'created_at', 'updated_at', 'place_guess', 'id_please',
       'observed_on_string', 'iconic_taxon_id',
       'num_identification_agreements', 'num_identification_disagreements',
       'time_observed_at', 'time_zone', 'location_is_exact', 'delta',
       'positional_accuracy', 'private_latitude', 'private_longitude',
       'geoprivacy', 'quality_grade', 'positioning_method',
       'positioning_device', 'out_of_range', 'license', 'uri',
       'observation_photos_count', 'comments_count', 'zic_time_zone',
       'oauth_application_id', 'observation_sounds_count',
       'identifications_count', 'captive', 'community_taxon_id', 'site_id',
       'old_uuid', 'public_positional_accuracy', 'mappable',
       'cached_votes_total', 'last_indexed_at', 'private_place_guess', 'uuid',
       'taxon_geoprivacy', 'short_description', 'user_login',
       'iconic_taxon_name', 'tag_list', 'faves_count', 'created_at_utc',
       'updated_at_utc', 'time_observed_at_utc',
       'owners_identification_from_vision', 'user', 'taxon_name', 'rank',
       'ancestry', 'common_name', 'common_name_id', 'common_name_name',
       'is_valid', 'lexicon', 'rank_level', 'medium_photo_url',
       'coordinates_obscured'],
      dtype='object')

In [6]:
len(df[df.description.isna()])

464

In [7]:
df2 = df
df2.description = df2.description.fillna('blank')
dead = df2[(df2.description.str.contains('dead')) |
           (df2.description.str.contains('dying'))  |
           (df2.description.str.contains('Dead')) |
           (df2.description.str.contains('Dying')) |
           (df2.description.str.contains('brown')) |
           (df2.description.str.contains('Brown'))
]
for desc in dead.description:
    print(desc)

Healthy to slightly stressed WRC near parking lot  Many dead/dying trees all around.
Dying back and with Coniophora growing on the bark
Dead
Group of mostly dead redcedars along the Wallace River.
Dead top
Dead
There are several cedars adjacent to the water channel that are thinning with brown tops.
Tops long dead
Dead young WRC
Yellowing and browning leafs. Soil is waterlogged in the park.

In [8]:
dead

,Unnamed: 0,id,observed_on,description,latitude,longitude,map_scale,timeframe,species_guess,user_id,...,rank,ancestry,common_name,common_name_id,common_name_name,is_valid,lexicon,rank_level,medium_photo_url,coordinates_obscured
52,52,70855690,2021-03-08,Healthy to slightly stressed WRC near parking ...,47.680208,-122.256595,16.0,NaN,Western Redcedar,3898930,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
62,62,70800466,2021-03-07,Dying back and with Coniophora growing on the ...,47.178622,-122.499350,NaN,NaN,Thuja plicata,932255,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://static.inaturalist.org/photos/11514987...,NaN
139,139,70417532,2021-03-01,Dead,48.543369,-122.083239,NaN,NaN,western redcedar,4053163,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
145,145,70378160,2021-02-28,Group of mostly dead redcedars along the Walla...,47.866675,-121.671395,NaN,NaN,NaN,3898930,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
172,172,70328937,2021-02-27,Dead top,48.766993,-122.355556,NaN,NaN,western redcedar,46945,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
173,173,70328892,2021-02-27,Dead,48.770532,-122.355326,NaN,NaN,western redcedar,46945,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
223,223,70133946,2021-02-17,There are several cedars adjacent to the water...,45.482436,-122.715795,NaN,NaN,western redcedar,2137608,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
256,256,70015410,2021-02-22,Tops long dead,47.489153,-122.470806,NaN,NaN,thuya gÃ©ant,4039476,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
513,513,69120460,2021-02-05,Dead young WRC,47.625870,-122.294113,NaN,NaN,NaN,3898930,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://inaturalist-open-data.s3.amazonaws.com...,NaN
541,541,68986033,2021-02-02,Yellowing and browning leafs. Soil is waterlog...,49.213074,-123.141693,NaN,NaN,western redcedar,2823934,...,species,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,https://static.inaturalist.org/photos/11183834...,NaN

In [9]:
df['tree_health'] = 'healthy'

In [10]:
df.loc[(df.description.str.contains('dead')), 'tree_health'] = 'dead'
df.loc[(df.description.str.contains('Dead')), 'tree_health'] = 'dead'
df.loc[(df.description.str.contains('dying')), 'tree_health'] = 'unhealthy'
df.loc[(df.description.str.contains('Dying')), 'tree_health'] = 'unhealthy'

df.tree_health.value_counts()

healthy      592
dead           6
unhealthy      2
Name: tree_health, dtype: int64

In [11]:
df[df.medium_photo_url.isna()]

,Unnamed: 0,id,observed_on,description,latitude,longitude,map_scale,timeframe,species_guess,user_id,...,ancestry,common_name,common_name_id,common_name_name,is_valid,lexicon,rank_level,medium_photo_url,coordinates_obscured,tree_health
17,17,71021017,2021-03-11,blank,49.034407,-122.685370,NaN,NaN,NaN,4087933,...,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,NaN,NaN,healthy
140,140,70395827,2021-02-27,blank,47.546624,-121.837315,NaN,NaN,NaN,1389154,...,48460/47126/211194/136329/47375/47374/1150915/...,western redcedar,77887.0,western redcedar,True,English,70.0,NaN,NaN,healthy

In [12]:
df.loc[[25, 29, 44, 87, 145, 298, 417], 'tree_health'] = 'damaged'

In [13]:
df.loc[[30, 34, 48, 83, 113, 139, 162, 169, 173, 189, 358, 359, 362, 365, 366, 367, 368, 371, 
        396, 402, 403, 407, 419, 420, 421, 424, 425, 440, 441, 467, 471, 474, 475, 494, 495, 
        505, 530, 543, 549, 550, 552, 567, 575, 595], 'tree_health'] = 'dead'

In [14]:
df.loc[[54, 61, 63, 97, 121, 122, 123, 256, 257, 261], 'tree_health'] = 'dying'

In [15]:
df.loc[[12, 19, 84, 99, 110, 111, 120, 142, 204, 217, 218, 265, 274, 339, 348, 353, 389, 423,
        449, 451, 452, 518, 597], 'tree_health'] = 'unhealthy'

In [16]:
df.loc[[0, 18, 39, 42, 49, 60, 89, 93, 102, 105, 133, 141, 152, 160, 179, 180, 198, 203, 211,
        212, 213, 223, 224, 237, 246, 254, 269, 285, 309, 312, 329, 332, 380, 382, 384, 395, 
        398, 404, 412, 415, 431, 435, 438, 442, 460, 470, 492, 509, 513, 522, 542, 553, 563,
        577, 582, 591, 599], 'tree_health'] = 'brown'

In [17]:
df.tree_health.value_counts()

healthy      456
brown         57
dead          45
unhealthy     25
dying         10
damaged        7
Name: tree_health, dtype: int64

In [18]:
df.to_csv('classified_trees.csv', encoding='utf-8')